FROM golang:latest

WORKDIR /go/src/github.com/raunofreiberg/kyrene

ADD glide.yaml .
ADD glide.lock .

RUN curl https://glide.sh/get | sh
RUN glide install
RUN go get github.com/pilu/fresh

EXPOSE 8000

# Default is production build. This is overriden in development to use hot reloading.
CMD ["go build && ./kyrene"]