version: "2"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-go
    volumes:
      - .:/go/src/github.com/raunofreiberg/kyrene
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DB_NAME=kyrene
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db # database container alias - db in this case
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; go build && ./kyrene'
  client:
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "8080:8080" # webpack-dev-server runs on 8080 by default
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - db
      - api
    depends_on:
      - db
      - api
    environment:
      - NODE_ENV=development
    command: npm run client
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ".data-postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kyrene
    restart: always