FROM golang:latest

WORKDIR /go/src/github.com/raunofreiberg/kyrene

ADD glide.yaml .
ADD glide.lock .

RUN curl https://glide.sh/get | sh
RUN glide install

EXPOSE 8000

# Build code and run the app
CMD ["go build && ./kyrene"]