version: "2"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=production      
    command: npm run build
  api: # Go server runs on :8000, /graphql route is proxied to via Nginx
    build:
      context: .
      dockerfile: Dockerfile-go
    volumes:
    - .:/go/src/github.com/raunofreiberg/kyrene
    links:
      - db
    depends_on:
      - db
    environment:
      - ENV=production
      - DB_NAME=kyrene
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db # database container alias - db in this case
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; go build && ./kyrene'
  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - .data-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kyrene
    restart: always
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./dist:/var/lib/assets
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    depends_on:
      - client
      - api